# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('metric_type', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('average', 'Average'), ('percentage', 'Percentage'), ('rate', 'Rate')], max_length=20, verbose_name='metric type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('query', models.TextField(help_text='SQL or ORM query to calculate the metric', verbose_name='query')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('refresh_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='refresh interval (minutes)')),
                ('last_calculated', models.DateTimeField(blank=True, null=True, verbose_name='last calculated')),
                ('last_value', models.JSONField(blank=True, default=dict, verbose_name='last value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dashboard metric',
                'verbose_name_plural': 'dashboard metrics',
                'db_table': 'dashboard_metrics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='period type')),
                ('period_start', models.DateTimeField(verbose_name='period start')),
                ('period_end', models.DateTimeField(verbose_name='period end')),
                ('metrics', models.JSONField(default=dict, verbose_name='metrics')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'analytics snapshot',
                'verbose_name_plural': 'analytics snapshots',
                'db_table': 'analytics_snapshots',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_s_period__f22dec_idx')],
                'unique_together': {('period_type', 'period_start', 'filters')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('report_type', models.CharField(choices=[('claims_summary', 'Claims Summary'), ('financial_summary', 'Financial Summary'), ('fraud_analysis', 'Fraud Analysis'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], max_length=30, verbose_name='report type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('query', models.TextField(blank=True, verbose_name='query')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('schedule', models.JSONField(blank=True, default=dict, verbose_name='schedule')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='next run')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='result')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='file path')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.report')),
            ],
            options={
                'verbose_name': 'report execution',
                'verbose_name_plural': 'report executions',
                'db_table': 'report_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
