# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('police_report', 'Police Report'), ('photos', 'Photos'), ('medical', 'Medical Records'), ('estimate', 'Repair Estimate'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('total_loss', 'Total Loss Report'), ('settlement', 'Settlement Agreement'), ('weather', 'Weather Report'), ('correspondence', 'Correspondence'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='claim_documents/', verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
            ],
            options={
                'verbose_name': 'claim document',
                'verbose_name_plural': 'claim documents',
                'db_table': 'claim_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_internal', models.BooleanField(default=True, verbose_name='internal note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'claim note',
                'verbose_name_plural': 'claim notes',
                'db_table': 'claim_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ai_assessment', 'AI Assessment'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repair_settlement', 'Repair/Settlement'), ('closed', 'Closed')], max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ai_assessment', 'AI Assessment'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repair_settlement', 'Repair/Settlement'), ('closed', 'Closed')], max_length=20, verbose_name='to status')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'claim status history',
                'verbose_name_plural': 'claim status histories',
                'db_table': 'claim_status_histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ai_assessment', 'AI Assessment'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repair_settlement', 'Repair/Settlement'), ('closed', 'Closed')], max_length=20, verbose_name='status')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False, verbose_name='system generated')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'claim timeline',
                'verbose_name_plural': 'claim timelines',
                'db_table': 'claim_timelines',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=20, unique=True, verbose_name='claim number')),
                ('incident_date', models.DateField(verbose_name='incident date')),
                ('incident_time', models.TimeField(blank=True, null=True, verbose_name='incident time')),
                ('incident_type', models.CharField(choices=[('collision', 'Collision'), ('comprehensive', 'Comprehensive'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('fire', 'Fire'), ('water_damage', 'Water Damage'), ('hail', 'Hail'), ('animal', 'Animal Strike'), ('glass', 'Glass Breakage'), ('other', 'Other')], max_length=20, verbose_name='incident type')),
                ('incident_severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('total_loss', 'Total Loss')], max_length=20, verbose_name='incident severity')),
                ('location', models.TextField(verbose_name='location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('number_of_vehicles', models.PositiveIntegerField(default=1, verbose_name='number of vehicles')),
                ('injuries', models.BooleanField(default=False, verbose_name='injuries')),
                ('injury_details', models.TextField(blank=True, verbose_name='injury details')),
                ('property_damage', models.BooleanField(default=False, verbose_name='property damage')),
                ('property_damage_details', models.TextField(blank=True, verbose_name='property damage details')),
                ('witnesses', models.BooleanField(default=False, verbose_name='witnesses')),
                ('witness_details', models.TextField(blank=True, verbose_name='witness details')),
                ('police_report', models.BooleanField(default=False, verbose_name='police report')),
                ('police_report_number', models.CharField(blank=True, max_length=50, verbose_name='police report number')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='claim amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('ai_assessment', 'AI Assessment'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repair_settlement', 'Repair/Settlement'), ('closed', 'Closed')], default='submitted', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='priority')),
                ('ai_assessment', models.JSONField(blank=True, default=dict, verbose_name='AI assessment')),
                ('fraud_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='fraud risk score')),
                ('total_loss_probability', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='total loss probability')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('assigned_adjuster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'claim',
                'verbose_name_plural': 'claims',
                'db_table': 'claims',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
