# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0002_initial'),
        ('policies', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimnote',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimtimeline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimtimeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['customer'], name='claims_custome_d90b87_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='claims_policy__d2422d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['vehicle'], name='claims_vehicle_24f04c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_status_cb731f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['incident_date'], name='claims_inciden_ecb07b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_adjuster'], name='claims_assigne_87720d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_investigator'], name='claims_assigne_dd8876_idx'),
        ),
    ]
