# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_claim_updates', models.BooleanField(default=True, verbose_name='email claim updates')),
                ('email_policy_updates', models.BooleanField(default=True, verbose_name='email policy updates')),
                ('email_payment_updates', models.BooleanField(default=True, verbose_name='email payment updates')),
                ('email_document_requests', models.BooleanField(default=True, verbose_name='email document requests')),
                ('email_ai_assessments', models.BooleanField(default=True, verbose_name='email AI assessments')),
                ('email_fraud_alerts', models.BooleanField(default=True, verbose_name='email fraud alerts')),
                ('email_settlements', models.BooleanField(default=True, verbose_name='email settlements')),
                ('email_marketing', models.BooleanField(default=False, verbose_name='email marketing')),
                ('push_claim_updates', models.BooleanField(default=True, verbose_name='push claim updates')),
                ('push_policy_updates', models.BooleanField(default=True, verbose_name='push policy updates')),
                ('push_payment_updates', models.BooleanField(default=True, verbose_name='push payment updates')),
                ('push_document_requests', models.BooleanField(default=True, verbose_name='push document requests')),
                ('push_ai_assessments', models.BooleanField(default=True, verbose_name='push AI assessments')),
                ('push_fraud_alerts', models.BooleanField(default=True, verbose_name='push fraud alerts')),
                ('push_settlements', models.BooleanField(default=True, verbose_name='push settlements')),
                ('sms_urgent_only', models.BooleanField(default=True, verbose_name='SMS urgent only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('claim', 'Claim Update'), ('policy', 'Policy Update'), ('payment', 'Payment'), ('document', 'Document Required'), ('ai_assessment', 'AI Assessment'), ('fraud_alert', 'Fraud Alert'), ('settlement', 'Settlement'), ('system', 'System'), ('reminder', 'Reminder')], max_length=20, verbose_name='type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='related object type')),
                ('related_object_id', models.CharField(blank=True, max_length=50, verbose_name='related object ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['sent_at'], name='notificatio_sent_at_eceac5_idx')],
            },
        ),
    ]
