# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='risk score')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='risk level')),
                ('risk_factors', models.JSONField(default=list, verbose_name='risk factors')),
                ('behavioral_indicators', models.JSONField(blank=True, default=list, verbose_name='behavioral indicators')),
                ('network_analysis', models.JSONField(blank=True, default=dict, verbose_name='network analysis')),
                ('ai_recommendation', models.TextField(verbose_name='AI recommendation')),
                ('status', models.CharField(choices=[('new', 'New'), ('investigation', 'Investigation'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='new', max_length=20, verbose_name='status')),
                ('investigator_notes', models.TextField(blank=True, verbose_name='investigator notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alert', to='claims.claim')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fraud alert',
                'verbose_name_plural': 'fraud alerts',
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='open', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='priority')),
                ('case_number', models.CharField(max_length=20, unique=True, verbose_name='case number')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('findings', models.TextField(blank=True, verbose_name='findings')),
                ('conclusion', models.TextField(blank=True, verbose_name='conclusion')),
                ('recommendation', models.TextField(blank=True, verbose_name='recommendation')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='estimated completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='claims.claim')),
                ('fraud_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='investigations.fraudalert')),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investigation',
                'verbose_name_plural': 'investigations',
                'db_table': 'investigations',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('statement', 'Statement'), ('surveillance', 'Surveillance'), ('digital', 'Digital Forensics'), ('financial', 'Financial Record'), ('medical', 'Medical Record'), ('other', 'Other')], max_length=20, verbose_name='evidence type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(blank=True, null=True, upload_to='investigation_evidence/', verbose_name='file')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='source')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_key_evidence', models.BooleanField(default=False, verbose_name='key evidence')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.investigation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investigation evidence',
                'verbose_name_plural': 'investigation evidence',
                'db_table': 'investigation_evidence',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_interview', models.BooleanField(default=False, verbose_name='interview note')),
                ('interviewee', models.CharField(blank=True, max_length=200, verbose_name='interviewee')),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='interview date')),
                ('is_confidential', models.BooleanField(default=True, verbose_name='confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_notes', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='investigations.investigation')),
            ],
            options={
                'verbose_name': 'investigation note',
                'verbose_name_plural': 'investigation notes',
                'db_table': 'investigation_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['risk_level'], name='fraud_alert_risk_le_2ab83d_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status'], name='fraud_alert_status_cf1609_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['assigned_investigator'], name='fraud_alert_assigne_9a40ce_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['claim'], name='investigati_claim_i_9f8c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['investigator'], name='investigati_investi_ccac49_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['status'], name='investigati_status_295316_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['case_number'], name='investigati_case_nu_fde1d8_idx'),
        ),
    ]
