# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='liability')),
                ('collision', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='collision')),
                ('comprehensive', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comprehensive')),
                ('uninsured_motorist', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='uninsured motorist')),
                ('medical_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='medical payments')),
                ('personal_injury_protection', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PIP')),
                ('roadside_assistance', models.BooleanField(default=False, verbose_name='roadside assistance')),
                ('rental_reimbursement', models.BooleanField(default=False, verbose_name='rental reimbursement')),
                ('glass_coverage', models.BooleanField(default=False, verbose_name='glass coverage')),
                ('dwelling', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='dwelling')),
                ('personal_property', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='personal property')),
                ('additional_living_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='additional living expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'policy coverage',
                'verbose_name_plural': 'policy coverages',
                'db_table': 'policy_coverages',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('policy', 'Policy Document'), ('declaration', 'Declaration Page'), ('endorsement', 'Endorsement'), ('binder', 'Binder'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='policy_documents/', verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'policy document',
                'verbose_name_plural': 'policy documents',
                'db_table': 'policy_documents',
            },
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'premium history',
                'verbose_name_plural': 'premium histories',
                'db_table': 'premium_history',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=20, unique=True, verbose_name='policy number')),
                ('type', models.CharField(choices=[('auto_comprehensive', 'Comprehensive Auto'), ('auto_collision', 'Collision Auto'), ('auto_liability', 'Liability Auto'), ('homeowners', 'Homeowners'), ('renters', 'Renters'), ('umbrella', 'Umbrella')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='premium')),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='deductible')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='annual', max_length=20, verbose_name='payment frequency')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('coverage', models.JSONField(default=dict, verbose_name='coverage')),
                ('property_address', models.TextField(blank=True, verbose_name='property address')),
                ('property_type', models.CharField(blank=True, max_length=50, verbose_name='property type')),
                ('property_year_built', models.IntegerField(blank=True, null=True, verbose_name='year built')),
                ('property_square_footage', models.IntegerField(blank=True, null=True, verbose_name='square footage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_policies', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'db_table': 'policies',
            },
        ),
    ]
