# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='policycoverage',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_details', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_policy_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premiumhistory',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_history', to='policies.policy'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_policy__ca1bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['customer'], name='policies_custome_09148f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status'], name='policies_status_d09338_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['start_date', 'end_date'], name='policies_start_d_34ca2f_idx'),
        ),
    ]
