# Generated by Django 5.0.6 on 2026-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('claim_agent', 'Claim Agent'), ('policy_agent', 'Policy Agent'), ('fraud_agent', 'Fraud Agent'), ('damage_agent', 'Damage Agent'), ('settlement_agent', 'Settlement Agent'), ('decision_agent', 'Decision Agent')], max_length=20, verbose_name='agent type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('input_data', models.JSONField(default=dict, verbose_name='input data')),
                ('output_data', models.JSONField(default=dict, verbose_name='output data')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='confidence')),
                ('processing_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='processing time (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'agent output',
                'verbose_name_plural': 'agent outputs',
                'db_table': 'agent_outputs',
            },
        ),
        migrations.CreateModel(
            name='ClaimAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('repair_cost', 'Repair Cost Prediction'), ('fraud_risk', 'Fraud Risk Assessment'), ('total_loss', 'Total Loss Prediction'), ('comprehensive', 'Comprehensive Assessment')], default='comprehensive', max_length=20, verbose_name='assessment type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('requires_review', 'Requires Review')], default='pending', max_length=20, verbose_name='status')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='model version')),
                ('predicted_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='predicted repair cost')),
                ('cost_breakdown', models.JSONField(blank=True, default=dict, verbose_name='cost breakdown')),
                ('repair_time_estimate_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='repair time estimate (days)')),
                ('comparable_claims_count', models.PositiveIntegerField(default=0, verbose_name='comparable claims count')),
                ('fraud_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='fraud risk score')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='risk level')),
                ('risk_factors', models.JSONField(blank=True, default=list, verbose_name='risk factors')),
                ('behavioral_indicators', models.JSONField(blank=True, default=list, verbose_name='behavioral indicators')),
                ('network_analysis', models.JSONField(blank=True, default=dict, verbose_name='network analysis')),
                ('total_loss_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='total loss probability')),
                ('claim_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='claim priority')),
                ('ai_recommendation', models.TextField(blank=True, verbose_name='AI recommendation')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='confidence')),
                ('contributing_factors', models.JSONField(blank=True, default=list, verbose_name='contributing factors')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='assessed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
            ],
            options={
                'verbose_name': 'claim assessment',
                'verbose_name_plural': 'claim assessments',
                'db_table': 'claim_assessments',
            },
        ),
        migrations.CreateModel(
            name='DecisionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agents', models.JSONField(default=list, verbose_name='agents')),
                ('rl_recommendation', models.JSONField(default=dict, verbose_name='RL recommendation')),
                ('final_decision', models.JSONField(default=dict, verbose_name='final decision')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='model version')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decided_by', models.CharField(blank=True, max_length=100, verbose_name='decided by')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'decision flow',
                'verbose_name_plural': 'decision flows',
                'db_table': 'decision_flows',
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('claim_assessment', 'Claim Assessment'), ('fraud_detection', 'Fraud Detection'), ('total_loss_prediction', 'Total Loss Prediction'), ('repair_cost_prediction', 'Repair Cost Prediction'), ('rl_optimizer', 'RL Optimizer')], max_length=30, verbose_name='model type')),
                ('version', models.CharField(max_length=50, verbose_name='version')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='accuracy')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='precision')),
                ('recall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='recall')),
                ('f1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F1 score')),
                ('mae', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MAE')),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RMSE')),
                ('r2_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='R² score')),
                ('auc', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='AUC')),
                ('training_samples', models.PositiveIntegerField(default=0, verbose_name='training samples')),
                ('validation_samples', models.PositiveIntegerField(default=0, verbose_name='validation samples')),
                ('test_samples', models.PositiveIntegerField(default=0, verbose_name='test samples')),
                ('training_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='training duration (seconds)')),
                ('hyperparameters', models.JSONField(default=dict, verbose_name='hyperparameters')),
                ('metrics', models.JSONField(default=dict, verbose_name='metrics')),
                ('artifact_path', models.CharField(blank=True, max_length=500, verbose_name='artifact path')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('trained_at', models.DateTimeField(verbose_name='trained at')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'model performance',
                'verbose_name_plural': 'model performances',
                'db_table': 'model_performances',
                'ordering': ['-trained_at'],
            },
        ),
    ]
