# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentoutput',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_outputs', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimassessment',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionflow',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_flow', to='claims.claim'),
        ),
        migrations.AlterUniqueTogether(
            name='modelperformance',
            unique_together={('model_type', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='agentoutput',
            unique_together={('claim', 'agent_type')},
        ),
        migrations.AddIndex(
            model_name='claimassessment',
            index=models.Index(fields=['claim'], name='claim_asses_claim_i_87d802_idx'),
        ),
        migrations.AddIndex(
            model_name='claimassessment',
            index=models.Index(fields=['status'], name='claim_asses_status_feb828_idx'),
        ),
        migrations.AddIndex(
            model_name='claimassessment',
            index=models.Index(fields=['assessed_at'], name='claim_asses_assesse_ca1bd6_idx'),
        ),
    ]
