# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='make')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('year', models.IntegerField(verbose_name='year')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('color', models.CharField(max_length=30, verbose_name='color')),
                ('license_plate', models.CharField(max_length=20, verbose_name='license plate')),
                ('license_state', models.CharField(max_length=2, verbose_name='license state')),
                ('registration_expiry', models.DateField(verbose_name='registration expiry')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase price')),
                ('current_mileage', models.IntegerField(default=0, verbose_name='current mileage')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('plugin_hybrid', 'Plug-in Hybrid')], default='gasoline', max_length=20, verbose_name='fuel type')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], default='automatic', max_length=20, verbose_name='transmission')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('total_loss', 'Total Loss'), ('salvage', 'Salvage'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='engine size (L)')),
                ('body_style', models.CharField(blank=True, max_length=30, verbose_name='body style')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='policies.policy')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('inspection', 'Inspection Report'), ('title', 'Title'), ('bill_of_sale', 'Bill of Sale'), ('insurance_card', 'Insurance Card'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='vehicle_documents/', verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'vehicle document',
                'verbose_name_plural': 'vehicle documents',
                'db_table': 'vehicle_documents',
            },
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='event type')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='mileage')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('performed_by', models.CharField(blank=True, max_length=100, verbose_name='performed by')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'vehicle history',
                'verbose_name_plural': 'vehicle histories',
                'db_table': 'vehicle_histories',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate', 'license_state'], name='vehicles_license_e21feb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer'], name='vehicles_custome_a752bc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['policy'], name='vehicles_policy__72eac2_idx'),
        ),
    ]
