# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20, unique=True, verbose_name='customer number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='license number')),
                ('license_state', models.CharField(blank=True, max_length=2, verbose_name='license state')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='license expiry')),
                ('credit_score', models.IntegerField(blank=True, null=True, verbose_name='credit score')),
                ('risk_rating', models.CharField(blank=True, max_length=20, verbose_name='risk rating')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'ID Document'), ('license', 'Driver License'), ('insurance', 'Insurance Card'), ('registration', 'Registration'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='customer_documents/', verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer document',
                'verbose_name_plural': 'customer documents',
                'db_table': 'customer_documents',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customers_custome_41ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='customers_user_id_5b5af9_idx'),
        ),
    ]
