# Generated by Django 5.0.6 on 2026-10-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(max_length=20, unique=True, verbose_name='settlement number')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='estimated amount')),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='deductible')),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='approved amount')),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='calculated', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer (ACH)'), ('wire', 'Wire Transfer'), ('check', 'Check'), ('digital_wallet', 'Digital Wallet'), ('card', 'Card')], default='bank_transfer', max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='payment reference')),
                ('bank_account', models.JSONField(blank=True, default=dict, verbose_name='bank account details')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='claims.claim')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'settlement',
                'verbose_name_plural': 'settlements',
                'db_table': 'settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=20, unique=True, verbose_name='payment number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer (ACH)'), ('wire', 'Wire Transfer'), ('check', 'Check'), ('digital_wallet', 'Digital Wallet'), ('card', 'Card')], max_length=20, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='payment reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='settlements.settlement')),
            ],
            options={
                'verbose_name': 'settlement payment',
                'verbose_name_plural': 'settlement payments',
                'db_table': 'settlement_payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], max_length=20, verbose_name='status')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='settlements.settlement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'settlement timeline',
                'verbose_name_plural': 'settlement timelines',
                'db_table': 'settlement_timelines',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settlement_number'], name='settlements_settlem_21b626_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['claim'], name='settlements_claim_i_e7d311_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['customer'], name='settlements_custome_f69178_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status'], name='settlements_status_18dd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payment_status'], name='settlements_payment_1a5e07_idx'),
        ),
    ]
